### ISSUE TITLE
Make the game more interesting

### ISSUE THREAD

**Issue by ashish4321** [ashish4321/Rock-Paper-and-Scissors-game#1]

**Comment by felipemfarias** [comment]
I'll take this

**Comment by cedric-h** [comment]
Definitely willing to do a take on this. Here are some of my ideas, lemme know what'll fly:

-  Port game to canvas. This'll give us the ability to have fun special effects and what not
-  Make it so that each player has a certain amount of health, and in order to win you have to take away all of their health. Each time you win a match, you take away a portion of their health, so that several matches must be completed to defeat your enemy.
-  Add some strategic elements. Rock paper scissors, in it's purest form, is based entirely upon luck. What if we make it so that when one wins a match, they earn some points, and then can spend these points to buy upgrades for their rock, paper, or pair of scissors, and can also purchase armor for themselves that has a chance to block attacks. Rocks, for example, could have the highest chance of being blocked, but do the most damage. Scissors could have a medium chance of being blocked, and do medium damage. Paper could do very little damage, but be blocked almost never. Perhaps you could upgrade your scissors into shears, to give them a higher damage and lesser chance of being blocked, and then into a sword for an even more devastating effect. Eventually, you could upgrade them into a laser sword, which would do tons of damage. Perhaps you could upgrade your rock into a catapult, then a trebuchet, and then a missile. Paper, perhaps, could be upgraded into... um... construction paper? No, from paper to then a needle, to a laser, ect. This way, the player feel as if they are improving as they play.

**Comment by cedric-h** [comment]
I'll get started on canvas right away, because we'll need that no matter what. I'll wait for you to give me an okay or a no go for the last two.

**Comment by cedric-h** [comment]
Got canvas set up, working on the start screen.

**Comment by cedric-h** [comment]
Added pull request. Not quite finished, but I wanted to get it in before hacktoberfest is done with. Going to add RPS based attacks soon, right now the attacks do damage regardless of RPS system.

**Comment by cedric-h** [comment]
Working on crafting system, item spawning from the portal. I might... maybe... be making rock paper scissors to complicated? No, that's impossible.
